yolo_obb_bev_detector_node:
  ros__parameters:
    input_topic: /rslidar_points
    expected_frame_id: rslidar
    output_frame: rslidar

    model_path: /home/edv/ros2_ws/bev_dataset/models/rack_bev_obb_yolo26m_v4m_racksv2_best_epoch40.pt

    roi_min: [-14.5, -15.0, -2.0]
    roi_max: [9.0, 6.0, 3.0]
    resolution_m_per_px: 0.01

    density_clip_count: 12
    min_points_in_roi: 1000

    inference_interval_sec: 1.0
    imgsz: 1024

    model_confidence_threshold: 0.03
    confidence_threshold: 0.03
    iou_threshold: 0.50

    tile_size_px: 1024
    tile_overlap_ratio: 0.25
    side_confidence_threshold: 0.20
    top_confidence_threshold: 0.05
    obb_nms_iou_threshold: 0.20

    deduplicate_physical_racks: true
    physical_merge_distance_m: 0.45
    physical_merge_iou_threshold: 0.05
    physical_prefer_side_visible: true

    device: "0"

    marker_size: [1.05, 1.05, 2.00]
    marker_yaw_mode: fixed
    marker_fixed_yaw_rad: -0.3926990817
    marker_yaw_snap_step_deg: 90.0
    marker_yaw_snap_offset_deg: 0.0
    rack_floor_z: -0.95
    marker_alpha: 0.35
    text_marker_enabled: true
    marker_lifetime_sec: 2.5

    track_enabled: true
    track_match_distance_m: 0.50
    track_yaw_gate_deg: 45.0
    track_min_iou: 0.02
    track_max_match_cost: 2.40
    track_confirm_hits: 2
    track_instant_confirm_confidence: 0.45
    track_max_missed_sec: 8.0
    track_tentative_timeout_sec: 3.0
    track_position_alpha: 0.25
    track_yaw_alpha: 0.20
    track_confidence_alpha: 0.35

    marker_topic: /detection/rack_obb_markers
    centroid_topic: /detection/rack_centroids
    json_topic: /detection/rack_detections_json
    stable_track_topic: /tracking/stable_tracks
    publish_stable_tracks: true
    stable_track_include_lost: true

    publish_tracking_centroids: false

track_manager_node:
  ros__parameters:
    target_frame: rslidar
    use_stable_tracks_input: true
    stable_track_topic: /tracking/stable_tracks
    stable_track_include_lost: true
